name: CI-CD

on:
  push:
    branches: ["github-action"]
  pull_request:
    branches: ["github-action"]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REACTUSERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfile
          push: true
          tags: ${{ secrets.REACTUSERNAME }}/react-vite-template:latest

  # push_to_vercel:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: amondnet/vercel-action@v20
  #       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.ORG_ID}}
  #         vercel-project-id: ${{ secrets.PROJECT_ID}}
  #         vercel-args: "--prod"
